Global:
  use_gpu: True
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/rec_r50_vd_srn_ch
  save_epoch_step: 100
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 5000]
  cal_metric_during_train: True
  pretrained_model: ../pretrain_models/rec_r50_vd_srn_train/best_accuracy
  checkpoints: ./output/rec_r50_vd_srn_ch/best_accuracy
  save_inference_dir: ./output/rec_r50_vd_srn_ch/best_accuracy
  use_visualdl: False
  infer_img: ./demo/art_train_gt_577_1_shopsign_1.0_image.jpg
  # for data or label process
  character_dict_path: ../ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  num_heads: 8
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec_r50_vd_srn_ch/predicts_srn.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset_rec
    label_file_list:
      - D:/ocr_dataset_rec/art_reg_train_train.txt
      # - D:/ocr_dataset_rec/art_reg_train_val.txt
      - D:/ocr_dataset_rec/baidu_scene_ch_reg_train_train.txt
      # - D:/ocr_dataset_rec/baidu_scene_ch_reg_train_val.txt
      - D:/ocr_dataset_rec/icdar2017rctw_reg_train_train.txt
      # - D:/ocr_dataset_rec/icdar2017rctw_reg_train_val.txt
      - D:/ocr_dataset_rec/lsvt_reg_train_train.txt
      # - D:/ocr_dataset_rec/lsvt_reg_train_val.txt
      - D:/ocr_dataset_rec/rects_reg_train_train.txt
      # - D:/ocr_dataset_rec/rects_reg_train_val.txt
      # - D:/ocr_dataset_rec/360w_train.txt
    ratio_list: [ 1.0, 1.0, 1.0, 1.0, 1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: False
    batch_size_per_card: 16
    drop_last: False
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset_rec
    label_file_list:
      # - D:/ocr_dataset_rec/art_reg_train_val.txt
      # - D:/ocr_dataset_rec/icdar2017rctw_reg_train_val.txt
      # - D:/ocr_dataset_rec/lsvt_reg_train_val.txt
      - D:/ocr_dataset_rec/rects_reg_train_val.txt
    # ratio_list: [ 1.0, 1.0, 1.0, 1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [1, 64, 256]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 0
