Global:
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/rec_r34_vd_tps_bilstm_ctc
  save_epoch_step: 10
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 5000]
  cal_metric_during_train: True
  pretrained_model: ../pretrain_models/rec_r34_vd_tps_bilstm_ctc_v2.0_train/best_accuracy
  checkpoints: ./output/rec_r34_vd_tps_bilstm_ctc/best_accuracy
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ../ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_r34_vd_tps_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: STARNet
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 0.1
    model_name: large
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset_rec
    label_file_list: [ D:/ocr_dataset_rec/art_reg_train_train.txt, D:/ocr_dataset_rec/baidu_scene_ch_reg_train_train.txt, D:/ocr_dataset_rec/icdar2017rctw_reg_train_train.txt, D:/ocr_dataset_rec/lsvt_reg_train_train.txt, D:/ocr_dataset_rec/rects_reg_train_train.txt ]
    ratio_list: [ 1.0, 1.0, 1.0, 1.0, 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset_rec
    label_file_list:
      # - D:/ocr_dataset_rec/art_reg_train_val.txt
      # - D:/ocr_dataset_rec/icdar2017rctw_reg_train_val.txt
      # - D:/ocr_dataset_rec/lsvt_reg_train_val.txt
      - D:/ocr_dataset_rec/rects_reg_train_val.txt
    # ratio_list: [ 1.0, 1.0, 1.0, 1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 0
