Global:
  use_gpu: true
  epoch_num: 5000
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: ./output/det_sast_r50_vd_ch/
  save_epoch_step: 1000
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 5000]
  cal_metric_during_train: False
  pretrained_model: ./output/det_sast_r50_vd_ch/best_accuracy
  checkpoints: ./output/det_sast_r50_vd_ch/best_accuracy
  save_inference_dir: ./output/det_sast_r50_vd_ch/best_accuracy
  use_visualdl: False
  infer_img: 
  save_res_path: ./output/det_sast_r50_vd_ch/predicts_sast.txt

Architecture:
  model_type: det
  algorithm: SAST
  Transform:
  Backbone:
    name: ResNet_SAST
    layers: 50
  Neck:
    name: SASTFPN
    with_cab: True
  Head:
    name: SASTHead

Loss:
  name: SASTLoss
  
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
  #  name: Cosine
    learning_rate: 0.001
  #  warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: SASTPostProcess
  score_thresh: 0.5
  sample_pts_num: 6
  nms_thresh: 0.2
  expand_scale: 1.2
  shrink_ratio_of_width: 0.2

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset
    label_file_list: [ D:/ocr_dataset/art_train_train.txt, D:/ocr_dataset/icdar2017rctw_train_train.txt, D:/ocr_dataset/lsvt_train_train.txt, D:/ocr_dataset/rects_train_train.txt ]
    ratio_list: [ 1.0, 1.0, 1.0, 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - SASTProcessTrain:
          image_shape: [512, 512]
          min_crop_side_ratio: 0.3
          min_crop_size: 24
          min_text_size: 4
          max_text_size: 512
      - KeepKeys:
          keep_keys: ['image', 'score_map', 'border_map', 'training_mask', 'tvo_map', 'tco_map'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:/ocr_dataset
    label_file_list:
      # - D:/ocr_dataset/art_train_val.txt
      # - D:/ocr_dataset/icdar2017rctw_train_val.txt
      # - D:/ocr_dataset/lsvt_train_val.txt
      - D:/ocr_dataset/rects_train_val.txt
    # ratio_list: [ 1.0, 1.0, 1.0, 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          resize_long: 768
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 0